name: Flutter CI

on: push

env:
  PLATFORM: linux-x64
  APP_NAME: darts-automation

jobs:
  build-and-release-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.16.5'

      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install project dependencies
        run: flutter pub get

      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Enable linux build
        run: flutter config --enable-linux-desktop

      - name: Build artifact
        id: build
        run: flutter build linux --release --target-platform ${{ env.PLATFORM }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./
            !android
            !windows
            !ios
            !macos
            !web
